import Section from "@/components/Section";
import Seo from "@/components/Seo";
import { EMAIL, PHONE, ADDRESS } from "@/lib/constants";

const PrivacyPolicy = () => {
  return (
    <div className="pt-20">
      <Seo
        title="Privacy Policy | Rim Country Inn Payson AZ"
        description="How Rim Country Inn collects, uses, and protects guest information at our Payson, AZ hotel and on this website."
        path="/privacy-policy"
        breadcrumbs={[{ name: "Home", path: "/" }, { name: "Privacy Policy", path: "/privacy-policy" }]}
      />
      <Section className="py-16 md:py-24">
        <div className="max-w-3xl mx-auto prose prose-neutral dark:prose-invert">
          <h1 className="font-display text-3xl md:text-4xl font-bold text-foreground mb-2">
            Rim Country Inn — Privacy Policy
          </h1>
          <p className="text-muted-foreground text-sm mb-8">
            Last updated: September 16, 2026
          </p>

          <p className="text-muted-foreground leading-relaxed">
            This Privacy Policy explains how Rim Country Inn ("we," "us," or "our") collects, uses, shares, and protects information when you visit our website, make a reservation, or stay at our property located at {ADDRESS}. It works alongside our Terms &amp; Conditions.
          </p>
          <p className="text-muted-foreground leading-relaxed mt-3">
            By using our website or services, you agree to the practices described here.
          </p>

          <h2 className="font-display text-xl font-semibold text-foreground mt-10 mb-3">
            1. Information We Collect
          </h2>
          <ul className="list-disc pl-6 text-muted-foreground space-y-2">
            <li>
              <strong className="text-foreground">Reservation and contact information</strong> — name, email address, phone number, mailing address, and booking details.
            </li>
            <li>
              <strong className="text-foreground">Payment information</strong> — processed securely through our booking platform (Cloudbeds) and payment processors. We do not store full payment card numbers on our own systems.
            </li>
            <li>
              <strong className="text-foreground">Stay and operational information</strong> — reservation dates, room assignment, access-code activity, and other data generated by our automated check-in and property systems.
            </li>
            <li>
              <strong className="text-foreground">Communications</strong> — messages you send us and messages we send you (email and SMS).
            </li>
            <li>
              <strong className="text-foreground">Website and usage information</strong> — limited technical data such as device and browser type and general site interactions.
            </li>
          </ul>

          <h2 className="font-display text-xl font-semibold text-foreground mt-10 mb-3">
            2. How We Use Your Information
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-3">
            We use your information to:
          </p>
          <ul className="list-disc pl-6 text-muted-foreground space-y-2">
            <li>process and manage reservations and payments;</li>
            <li>operate our automated, keyless check-in and check-out systems;</li>
            <li>communicate with you about your stay;</li>
            <li>secure and maintain the property;</li>
            <li>comply with legal and tax obligations; and</li>
            <li>understand and improve our operations and guest experience.</li>
          </ul>

          <h2 className="font-display text-xl font-semibold text-foreground mt-10 mb-3">
            3. How We Share Information
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-3">
            We share information only as needed to run our business:
          </p>
          <ul className="list-disc pl-6 text-muted-foreground space-y-2">
            <li>
              <strong className="text-foreground">Service providers.</strong> With the platforms and vendors that help us operate — our booking platform, payment processors, and messaging providers — who may use the information only to provide services to us.
            </li>
            <li>
              <strong className="text-foreground">Legal and safety.</strong> When required by law or legal process, or to protect the rights, property, or safety of our guests, staff, or the property.
            </li>
            <li>
              <strong className="text-foreground">Business transfers.</strong> In connection with a merger, sale, or transfer of our business or assets.
            </li>
          </ul>
          <p className="text-muted-foreground leading-relaxed mt-3">
            We do not sell your personal contact information, and we do not share your mobile number or SMS opt-in information with third parties for their marketing purposes.
          </p>

          <h2 className="font-display text-xl font-semibold text-foreground mt-10 mb-3">
            4. SMS / Text Messaging Program
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-3">
            Because we operate a fully automated property, text messaging is part of how we deliver your stay.
          </p>
          <ul className="list-disc pl-6 text-muted-foreground space-y-2">
            <li>
              <strong className="text-foreground">What you receive.</strong> When you provide a mobile number during booking or check-in, we send transactional, service-related messages essential to your stay — including door access codes, check-in instructions, room assignments, and stay updates.
            </li>
            <li>
              <strong className="text-foreground">Message frequency.</strong> Typically 2–5 messages per stay.
            </li>
            <li>
              <strong className="text-foreground">Rates.</strong> Message and data rates may apply and are billed by your mobile carrier.
            </li>
            <li>
              <strong className="text-foreground">Use of your number.</strong> Your mobile number is used only for these transactional, stay-related purposes. We do not sell it, and we do not share it with third parties for their marketing or promotional purposes.
            </li>
            <li>
              <strong className="text-foreground">Help.</strong> For assistance with messages, contact us at{" "}
              <a href={`mailto:${EMAIL}`} className="text-primary hover:underline">{EMAIL}</a>{" "}
              or <a href={`tel:${PHONE}`} className="text-primary hover:underline">{PHONE}</a>.
            </li>
          </ul>

          <h2 className="font-display text-xl font-semibold text-foreground mt-10 mb-3">
            5. Payment Information
          </h2>
          <p className="text-muted-foreground leading-relaxed">
            Payments are handled through third-party booking and payment platforms that maintain their own security standards (including PCI-DSS compliance). We do not store complete payment card numbers on our systems, and we do not include payment card data in any information shared with analytics or research partners.
          </p>

          <h2 className="font-display text-xl font-semibold text-foreground mt-10 mb-3">
            6. Data Retention
          </h2>
          <p className="text-muted-foreground leading-relaxed">
            We keep information for as long as needed to provide our services, meet legal, accounting, and tax requirements, and resolve disputes. When information is no longer needed, we take reasonable steps to delete or de-identify it. Information that has been de-identified or aggregated — so that it does not reasonably identify you, and excluding payment card numbers, government identifiers, and precise geolocation — may be retained and shared with research, analytics, and technology partners for research and business purposes. Such partners are contractually required to use it only for agreed purposes, make no attempt to re-identify any individual, maintain reasonable security safeguards, and not further sell it.
          </p>

          <h2 className="font-display text-xl font-semibold text-foreground mt-10 mb-3">
            7. Security
          </h2>
          <p className="text-muted-foreground leading-relaxed">
            We use reasonable administrative, technical, and physical safeguards to protect your information. No system is completely secure, however, and we cannot guarantee absolute security.
          </p>

          <h2 className="font-display text-xl font-semibold text-foreground mt-10 mb-3">
            8. Your Privacy Rights
          </h2>
          <p className="text-muted-foreground leading-relaxed">
            Depending on your state of residence, you may have rights regarding your personal information, such as the right to access, correct, or delete it. To make a request or ask a question about your information, contact us at{" "}
            <a href={`mailto:${EMAIL}`} className="text-primary hover:underline">{EMAIL}</a>. We will respond consistent with applicable law. We will not deny you goods or services for exercising your rights.
          </p>

          <h2 className="font-display text-xl font-semibold text-foreground mt-10 mb-3">
            9. Children's Privacy
          </h2>
          <p className="text-muted-foreground leading-relaxed">
            Our website and services are not directed to children, and we do not knowingly collect personal information from children under 13. If you believe a child has provided us information, contact us and we will delete it.
          </p>

          <h2 className="font-display text-xl font-semibold text-foreground mt-10 mb-3">
            10. Third-Party Websites
          </h2>
          <p className="text-muted-foreground leading-relaxed">
            Our website and booking links may lead to third-party sites (such as booking platforms) that have their own privacy policies. We are not responsible for the practices of those third parties.
          </p>

          <h2 className="font-display text-xl font-semibold text-foreground mt-10 mb-3">
            11. Changes to This Policy
          </h2>
          <p className="text-muted-foreground leading-relaxed">
            We may update this Privacy Policy from time to time. Changes take effect when posted here with a revised "Last updated" date.
          </p>

          <h2 className="font-display text-xl font-semibold text-foreground mt-10 mb-3">
            12. Contact Us
          </h2>
          <p className="text-muted-foreground leading-relaxed">
            Rim Country Inn
            <br />
            {ADDRESS}
            <br />
            Email: <a href={`mailto:${EMAIL}`} className="text-primary hover:underline">{EMAIL}</a>
          </p>
        </div>
      </Section>
    </div>
  );
};

export default PrivacyPolicy;
